# lib/an_assertion_error.py
assert(1 == 1)
print("Assertion passed!")